DentalManagement.Admin/Controllers/CustomerController.cs
using DentalManagement.ApiIntegration.ApiIntegrations;
using DentalManagement.Utilities.Constants;
using DentalManagement.ViewModels.Catalog.Customers;
using FluentValidation;
using FluentValidation.AspNetCore;
using FluentValidation.Results;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DentalManagement.Admin.Controllers
{
    [Authorize]
    public class CustomerController : BaseController
    {
        private readonly ICustomerApiClient _customerApiClient;
        private readonly IConfiguration _configuration;
        private readonly IValidator<CustomerCreateRequest> _customerCreateRequestValidator;
        private readonly IValidator<CustomerUpdateRequest> _customerUpdateRequestValidator;

        public CustomerController(ICustomerApiClient customerApiClient, IConfiguration configuration, IValidator<CustomerCreateRequest> customerCreateRequestValidator, IValidator<CustomerUpdateRequest> customerUpdateRequestValidator)
        {
            _customerApiClient = customerApiClient;
            _configuration = configuration;
            _customerCreateRequestValidator = customerCreateRequestValidator;
            _customerUpdateRequestValidator = customerUpdateRequestValidator;
        }

        public async Task<IActionResult> Index(string keyword, int pageIndex = 1, int pageSize = 10)
        {
            ViewBag.Keyword = keyword;
            ViewBag.PageSize = pageSize;
            var request = new GetCustomerPagingRequest()
            {
                Keyword = keyword,
                PageIndex = pageIndex,
                PageSize = pageSize
            };
            var data = await _customerApiClient.GetAllPaging(request);
            return View(data);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var result = await _customerApiClient.GetById(id);
            if (!result.IsSuccessed)
            {
                TempData["errorMsg"] = SystemConstants.AppErrorMessage.NotFound;
                return RedirectToAction("Index");
            }
            return View(result.Data);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CustomerCreateRequest request)
        {
            ValidationResult result = await _customerCreateRequestValidator.ValidateAsync(request);
            if (!result.IsValid)
            {
                result.AddToModelState(this.ModelState);
                return View("Create", request);
            }
            var data = await _customerApiClient.Create(request);
            if (!data.IsSuccessed)
            {
                return View(request);
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var result = await _customerApiClient.GetById(id);
            if (result.IsSuccessed)
            {
                var customer = result.Data;
                var updateRequest = new CustomerUpdateRequest()
                {
                    FullName = customer.FullName,
                    Gender = customer.Gender,
                    BirthDay = customer.BirthDay,
                    Address = customer.Address,
                    PhoneNumber = customer.PhoneNumber,
                    EmailAddress = customer.EmailAddress,
                    IdentifyCard = customer.IdentifyCard,
                    Description = customer.Description,
                };
                return View(updateRequest);
            }
            return RedirectToAction("Error", "Home");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(CustomerUpdateRequest request)
        {
            ValidationResult result = await _customerUpdateRequestValidator.ValidateAsync(request);
            if (!result.IsValid)
            {
                result.AddToModelState(this.ModelState);
                return View("Edit", request);
            }
            var data = await _customerApiClient.Update(request);
            if (data == null)
            {
                return View(request);
            }
            return RedirectToAction("Index");
        }
    }
}

DentalManagement.Admin/Controllers/UserController.cs
using DentalManagement.ApiIntegration.ApiIntegrations;
using DentalManagement.ViewModels.Catalog.Users;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.IdentityModel.Logging;
using Microsoft.IdentityModel.Tokens;
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;

namespace DentalManagement.Admin.Controllers
{
    [Authorize]
    public class UserController : BaseController
    {

        private readonly IUserApiClient _userApiClient;
        private readonly IConfiguration _configuration;
        public UserController(IUserApiClient userApiClient, IConfiguration configuration)
        {
            _userApiClient = userApiClient;
            _configuration = configuration;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            HttpContext.Session.Remove("Token");
            return RedirectToAction("Index", "Login");
        }
    }
}

DentalManagement.Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Quản lý nha khoa</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">
    <link rel="shortcut icon" href="/assets/img/favicon.ico">
    <link href="/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="/assets/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="/assets/css/dataTables.bootstrap4.min.css" rel="stylesheet" type="text/css">
    <link href="/assets/css/bootstrap-datetimepicker.min.css" rel="stylesheet" type="text/css">
    <link href="/assets/css/select2.min.css" rel="stylesheet" type="text/css">
    <link href="/assets/css/style.css" rel="stylesheet" type="text/css">
</head>
<body>
    <div class="main-wrapper">
        <partial name="_Navbar" />
        <partial name="_Sidebar" />
        @RenderBody()
    </div>
    <div class="sidebar-overlay" data-reff=""></div>
    <script src="/assets/js/jquery-3.2.1.min.js"></script>
    <script src="/assets/js/popper.min.js"></script>
    <script src="/assets/js/bootstrap.min.js"></script>
    <script src="/assets/js/jquery.dataTables.min.js"></script>
    <script src="/assets/js/dataTables.bootstrap4.min.js"></script>
    <script src="/assets/js/select2.min.js"></script>
    <script src="/assets/js/jquery.slimscroll.js"></script>
    <script src="/assets/js/moment.min.js"></script>
    <script src="/assets/js/bootstrap-datetimepicker.min.js"></script>
    <script src="/assets/js/canvasjs.min.js"></script>
    <script src="/assets/js/app.js"></script>
    <script src="/assets/js/admin.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

DentalManagement.Admin/Views/Shared/_Navbar.cshtml
<div class="header">
    <div class="header-left">
        <a asp-action="Index" asp-controller="Home" class="logo">
            <img src="/assets/img/logo.png" width="35" height="35" alt="logo">
        </a>
    </div>
    <a id="toggle_btn" href="javascript:void(0);"><i class="fa fa-bars"></i></a>
    <a id="mobile_btn" class="mobile_btn float-left" href="#sidebar"><i class="fa fa-bars"></i></a>
    <ul class="nav user-menu float-right">
        <li class="nav-item dropdown has-arrow">
            <a href="#" class="dropdown-toggle nav-link user-link" data-toggle="dropdown">
                <span class="user-img">
                    <img class="rounded-circle" src="~/assets/img/user.jpg" width="24" alt="@User.Identity.Name">
                    <span class="status online"></span>
                </span>
                <span>@User.Identity.Name</span>
            </a>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="#"><i class="fa fa-user-circle-o"></i> Thông tin cá nhân</a>
                <a class="dropdown-item" href="#"><i class="fa fa-cog"></i> Cài đặt</a>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#sign_out">
                    <i class="fa fa-sign-out"></i> Đăng xuất
                </a>
            </div>
        </li>
    </ul>
    <div class="dropdown mobile-user-menu float-right">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
        <div class="dropdown-menu dropdown-menu-right">
            <a class="dropdown-item" href="#"><i class="fa fa-user-circle-o"></i> Thông tin cá nhân</a>
            <a class="dropdown-item" href="#"><i class="fa fa-cog"></i> Cài đặt</a>
            <a class="dropdown-item" href="#" data-toggle="modal" data-target="#sign_out">
                <i class="fa fa-sign-out"></i> Đăng xuất
            </a>
        </div>
    </div>
</div>
<div id="sign_out" class="modal fade delete-modal" role="dialog" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body text-center">
                <img src="~/assets/img/warning.png" alt="" width="50" height="46">
                <h3>Đăng xuất khỏi hệ thống?</h3>
                <div class="m-t-20">
                    <form method="post" asp-controller="User" asp-action="Logout">
                            <a href="#" class="btn btn-white" data-dismiss="modal">Hủy</a>
                            <button type="submit" class="btn btn-danger">Xác nhận</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

DentalManagement.Admin/Views/Shared/_Sidebar.cshtml
<div class="sidebar" id="sidebar">
    <div class="sidebar-inner slimscroll">
        <div id="sidebar-menu" class="sidebar-menu">
            <ul>
                <li class="menu-title">NHA KHOA THUẦN VIỆT</li>
                <li class="active">
                    <a asp-action="Index" asp-controller="Home"><i class="fa fa-dashboard"></i> <span>HỆ THỐNG</span></a>
                </li>
                <li>
                    <a asp-action="Index" asp-controller="Customer"><i class="fa fa-user"></i> <span>QUẢN LÝ KHÁCH HÀNG</span></a>
                </li>
            </ul>
        </div>
    </div>
</div>