DentalManagement.Admin/Controllers/Components/PagerViewComponent.cs
using DentalManagement.ViewModels.Common;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DentalManagement.Admin.Controllers.Components
{
    public class PagerViewComponent : ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync(PagedResultBase result)
        {
            return Task.FromResult((IViewComponentResult)View("Default", result));
        }
    }
}

DentalManagement.Admin/Controllers/ProductController.cs
using DentalManagement.ApiIntegration.ApiIntegrations;
using DentalManagement.ViewModels.Catalog.Products;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DentalManagement.Admin.Controllers
{
    [Authorize]
    public class ProductController : BaseController
    {
        private readonly IProductApiClient _productApiClient;
        private readonly IConfiguration _configuration;
        public ProductController(IProductApiClient productApiClient, IConfiguration configuration)
        {
            _productApiClient = productApiClient;
            _configuration = configuration;
        }
        public async Task<IActionResult> Index(string keyword, int pageIndex = 1, int pageSize = 10)
        {
            ViewBag.Keyword = keyword;
            ViewBag.PageSize = pageSize;
            var request = new GetProductPagingRequest()
            {
                Keyword = keyword,
                PageIndex = pageIndex,
                PageSize = pageSize
            };
            var data = await _productApiClient.GetAllPaging(request);
            return View(data);
        }

        [HttpGet]
        public async Task<IActionResult> GetProductList()
        {
            var productList = await _productApiClient.GetAll();
            return Ok(productList);
        }
    }
}

DentalManagement.Admin/Views/Product/Index.cshtml
@using DentalManagement.ViewModels.Common
@model PagedResult<DentalManagement.ViewModels.Catalog.Products.ProductViewModel>

@{
    ViewData["Title"] = "Danh sách dịch vụ";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Trang chủ</a></li>
        <li class="breadcrumb-item active">Dịch vụ</li>
    </ol>
    <h1 class="h3 mb-2 text-gray-800">Danh sách dịch vụ</h1>
    <div class="row">
        <div class="col-md-6 col-xs-12">
            <a type="button" class="btn btn-outline-primary" asp-action="Create" asp-controller="Product">
                <i class="fa fa-user-plus"></i>
                Tạo mới
            </a>
        </div>
        <div class="col-md-6 col-xs-12">
            <form asp-action="Index" asp-controller="Product" method="get">
                <div class="input-group">
                    <input type="text" class="form-control border-1 small" placeholder="Nhập từ khoá ..."
                           aria-label="Search" aria-describedby="basic-addon2" value="@ViewBag.Keyword" name="keyword">
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="submit">
                            <i class="fas fa-search fa-sm"></i>
                        </button>
                        <button class="btn btn-outline-primary" type="button" onclick="window.location.href='/Product/Index'">
                            X
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <hr />
    <!--number of record-->
    <div class="row">
        <form asp-action="Index" asp-controller="Product" method="get" name="pageSize">
            <div class="form-group">
                <div class="col-md-12">
                    <select class="form-control" onchange="numberOfRecords()">
                        <option value="10" selected>Số lượng hiển thị</option>
                        <option value="20">20 dịch vụ</option>
                        <option value="50">50 dịch vụ</option>
                        <option value="100">100 dịch vụ</option>
                    </select>
                </div>
            </div>
        </form>
    </div>
    <div class="card shadow mb-4">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-sm" width="100%" cellspacing="0">
                    <thead class="thead-dark">
                        <tr>
                            <th>
                            </th>
                            <th>
                                Loại dịch vụ
                            </th>
                            <th>
                                Tên dịch vụ
                            </th>
                            <th>
                                Đơn giá
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model.Items.Count == 0)
                        {
                            <tr>
                                <td colspan="5">Không có kết quả cho '@ViewBag.Keyword'</td>
                            </tr>
                        }
                        else
                        {
                            foreach (var item in Model.Items)
                            {
                                <tr>
                                    <td>
                                        <button type="button" class="btn" data-id="@item.Id">
                                            <i class="fas fa-plus-circle fa-sm"></i>
                                        </button>
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.ProductCategoryName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.UnitPrice)
                                    </td>
                                    <td>
                                        @Html.ActionLink(" Sửa", "Edit", new { id = item.Id }) |
                                        @Html.ActionLink("Xem", "Details", new { id = item.Id }) |
                                        @Html.ActionLink(" Xóa", "Delete", new { id = item.Id })
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
            @await Component.InvokeAsync("Pager", Model)
        </div>
    </div>
</div>