DentalManagement.Admin/Controllers/Components/PagerViewComponent.cs
using DentalManagement.ViewModels.Common;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DentalManagement.Admin.Controllers.Components
{
    public class PagerViewComponent : ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync(PagedResultBase result)
        {
            return Task.FromResult((IViewComponentResult)View("Default", result));
        }
    }
}

DentalManagement.Admin/Controllers/CustomerController.cs
using DentalManagement.ApiIntegration.ApiIntegrations;
using DentalManagement.Utilities.Constants;
using DentalManagement.ViewModels.Catalog.Customers;
using FluentValidation;
using FluentValidation.AspNetCore;
using FluentValidation.Results;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DentalManagement.Admin.Controllers
{
    [Authorize]
    public class CustomerController : BaseController
    {
        private readonly ICustomerApiClient _customerApiClient;
        private readonly IConfiguration _configuration;
        private readonly IValidator<CustomerCreateRequest> _customerCreateRequestValidator;
        private readonly IValidator<CustomerUpdateRequest> _customerUpdateRequestValidator;

        public CustomerController(ICustomerApiClient customerApiClient, IConfiguration configuration, IValidator<CustomerCreateRequest> customerCreateRequestValidator, IValidator<CustomerUpdateRequest> customerUpdateRequestValidator)
        {
            _customerApiClient = customerApiClient;
            _configuration = configuration;
            _customerCreateRequestValidator = customerCreateRequestValidator;
            _customerUpdateRequestValidator = customerUpdateRequestValidator;
        }

        public async Task<IActionResult> Index(string keyword, int pageIndex = 1, int pageSize = 10)
        {
            ViewBag.Keyword = keyword;
            ViewBag.PageSize = pageSize;
            var request = new GetCustomerPagingRequest()
            {
                Keyword = keyword,
                PageIndex = pageIndex,
                PageSize = pageSize
            };
            var data = await _customerApiClient.GetAllPaging(request);
            return View(data);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var result = await _customerApiClient.GetById(id);
            if (!result.IsSuccessed)
            {
                TempData["errorMsg"] = SystemConstants.AppErrorMessage.NotFound;
                return RedirectToAction("Index");
            }
            return View(result.Data);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CustomerCreateRequest request)
        {
            ValidationResult result = await _customerCreateRequestValidator.ValidateAsync(request);
            if (!result.IsValid)
            {
                result.AddToModelState(this.ModelState);
                return View("Create", request);
            }
            var data = await _customerApiClient.Create(request);
            if (!data.IsSuccessed)
            {
                return View(request);
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var result = await _customerApiClient.GetById(id);
            if (result.IsSuccessed)
            {
                var customer = result.Data;
                var updateRequest = new CustomerUpdateRequest()
                {
                    FullName = customer.FullName,
                    Gender = customer.Gender,
                    BirthDay = customer.BirthDay,
                    Address = customer.Address,
                    PhoneNumber = customer.PhoneNumber,
                    EmailAddress = customer.EmailAddress,
                    IdentifyCard = customer.IdentifyCard,
                    Description = customer.Description,
                };
                return View(updateRequest);
            }
            return RedirectToAction("Error", "Home");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(CustomerUpdateRequest request)
        {
            ValidationResult result = await _customerUpdateRequestValidator.ValidateAsync(request);
            if (!result.IsValid)
            {
                result.AddToModelState(this.ModelState);
                return View("Edit", request);
            }
            var data = await _customerApiClient.Update(request);
            if (data == null)
            {
                return View(request);
            }
            return RedirectToAction("Index");
        }
    }
}

DentalManagement.Admin/Views/Customer/Create.cshtml
@using DentalManagement.Data.Enums;
@using DentalManagement.ViewModels.Catalog.Customers;
@model CustomerCreateRequest

@{
    ViewData["Title"] = "Thêm mới khách hàng";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-wrapper">
    <div class="content">
        @*begin of content*@
        <div class="text-center">
            <h1 class="h4 text-gray-900 mb-4">Thêm mới khách hàng</h1>
        </div>
        <form class="user" asp-action="Create" asp-controller="Customer" method="post">
            <div class="form-group row">
                <div class="col-sm-3 mb-3 mb-sm-0">
                    <label asp-for="FullName" class="control-label"></label>
                    <input asp-for="FullName" class="form-control" />
                    <span asp-validation-for="FullName" class="text-danger d-block"></span>

                    <label asp-for="Gender" class="control-label"></label>
                    <select class="form-control" asp-for="Gender" asp-items="Html.GetEnumSelectList<Gender>()">
                        <option value="">-- Chọn giới tính --</option>
                    </select>
                    <span asp-validation-for="Gender" class="text-danger d-block"></span>

                    <label asp-for="BirthDay" class="control-label"></label>
                    <input asp-for="BirthDay" class="form-control" type="date" />
                    <span asp-validation-for="BirthDay" class="text-danger d-block"></span>

                </div>
                <div class="col-sm-3 mb-3 mb-sm-0">
                    <label asp-for="PhoneNumber" class="control-label"></label>
                    <input asp-for="PhoneNumber" class="form-control" />
                    <span asp-validation-for="PhoneNumber" class="text-danger d-block"></span>

                    <label asp-for="EmailAddress" class="control-label"></label>
                    <input asp-for="EmailAddress" class="form-control" />
                    <span asp-validation-for="EmailAddress" class="text-danger d-block"></span>

                    <label asp-for="IdentifyCard" class="control-label"></label>
                    <input asp-for="IdentifyCard" class="form-control" />
                    <span asp-validation-for="IdentifyCard" class="text-danger d-block"></span>

                </div>
                <div class="col-sm-6 mb-3 mb-sm-0">
                    <label asp-for="Address" class="control-label"></label>
                    <input asp-for="Address" class="form-control" />
                    <span asp-validation-for="Address" class="text-danger d-block"></span>

                    <label asp-for="Description" class="control-label"></label>
                    <textarea asp-for="Description" class="form-control" style="min-height: 108px;"></textarea>
                    <span asp-validation-for="Description" class="text-danger d-block"></span>

                </div>
            </div>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group row">
                <div class="col-sm-3">
                    @Html.ActionLink("Quay về", "Index", "Customer", "", new { @class = "btn btn-outline-dark" })
                    <button type="submit" class="btn btn-primary">Hoàn tất</button>
                </div>
            </div>
        </form>
        @*end of content*@
    </div>
</div>

DentalManagement.Admin/Views/Customer/Detail.cshtml
@model DentalManagement.ViewModels.Catalog.Customers.CustomerViewModel

@{
    ViewData["Title"] = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Detail</h1>

<div>
    <h4>CustomerViewModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FullName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BirthDay)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BirthDay)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmailAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmailAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdentifyCard)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdentifyCard)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

DentalManagement.Admin/Views/Customer/Edit.cshtml
@model DentalManagement.ViewModels.Catalog.Customers.CustomerUpdateRequest

@{
    ViewData["Title"] = "Cập nhật khách hàng";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Trang chủ</a></li>
        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Customer">Khách hàng</a></li>
        <li class="breadcrumb-item active">Cập nhật</li>
    </ol>
    <div class="text-center">
        <h1 class="h4 text-gray-900 mb-4">Cập nhật khách hàng</h1>
    </div>
    <form class="user" asp-controller="Customer" asp-action="Edit">
        <div class="form-group row">
            <div class="col-sm-3 mb-3 mb-sm-0">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />


                <label asp-for="Gender" class="control-label"></label>
                <select class="form-control" asp-for="Gender">
                    <option selected value="4">Chọn giới tính</option>
                    <option value="0">Nam</option>
                    <option value="1">Nữ</option>
                </select>


                <label asp-for="BirthDay" class="control-label"></label>
                <input asp-for="BirthDay" class="form-control" type="date" />

            </div>
            <div class="col-sm-3 mb-3 mb-sm-0">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />


                <label asp-for="EmailAddress" class="control-label"></label>
                <input asp-for="EmailAddress" class="form-control" />


                <label asp-for="IdentifyCard" class="control-label"></label>
                <input asp-for="IdentifyCard" class="form-control" />

            </div>
            <div class="col-sm-6 mb-3 mb-sm-0">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />


                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control" style="min-height: 108px;"></textarea>

            </div>
        </div>
        <span asp-validation-for="FullName" class="text-danger d-block"></span>
        <span asp-validation-for="Gender" class="text-danger d-block"></span>
        <span asp-validation-for="BirthDay" class="text-danger d-block"></span>
        <span asp-validation-for="PhoneNumber" class="text-danger d-block"></span>
        <span asp-validation-for="EmailAddress" class="text-danger d-block"></span>
        <span asp-validation-for="Address" class="text-danger d-block"></span>
        <span asp-validation-for="IdentifyCard" class="text-danger d-block"></span>
        <span asp-validation-for="Description" class="text-danger d-block"></span>
        <div class="form-group row">
            <div class="col-sm-3">
                <input asp-for="ModifiedBy" class="form-control" value="@User.Identity.Name" hidden />
                @Html.ActionLink("Quay về", "Index", "Customer", "", new { @class = "btn btn-outline-dark" })
                <button type="submit" class="btn btn-primary">Hoàn tất</button>
            </div>
        </div>
    </form>
</div>

DentalManagement.Admin/Views/Customer/Index.cshtml
@using DentalManagement.ViewModels.Common
@model PagedResult<DentalManagement.ViewModels.Catalog.Customers.CustomerViewModel>

@{
    ViewData["Title"] = "Danh sách khách hàng";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="page-wrapper">
    <div class="content">
        @*begin of content*@
        @if (TempData["successMsg"] != null)
        {
            <div id="alert-success-msg" class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>@TempData["successMsg"]</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        }
        @if (TempData["errorMsg"] != null)
        {
            <div id="alert-error-msg" class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong>@TempData["errorMsg"]</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        }
        <div class="row">
            <div class="col-md-6 col-xs-12">
                <h4 class="page-title">QUẢN LÝ KHÁCH HÀNG</h4>
            </div>
            <div class="col-md-6 col-xs-12">
                <a asp-action="Create" asp-controller="Customer" class="btn btn btn-primary btn-rounded float-right"><i class="fa fa-plus"></i> Thêm khách hàng</a>
            </div>
        </div>
        <hr />
        <div class="row filter-row">
            <!--number of record-->
            <div class="col-md-3 col-xs-12">
                <form asp-action="Index" asp-controller="Customer" method="get" name="pageSize">
                    <div class="form-group form-focus select-focus">
                        <label class="focus-label">Hiển thị</label>
                        <select class="select floating">
                            <option value="20">20 dòng dữ liệu</option>
                            <option value="50">50 dòng dữ liệu</option>
                            <option value="100">100 dòng dữ liệu</option>
                        </select>
                    </div>
                </form>
            </div>
            <!--search-->
            <div class="col-md-9 col-xs-12">
                <form asp-action="Index" asp-controller="Customer" method="get">
                    <div class="form-group form-focus">
                        <label class="focus-label">Tìm kiếm theo họ tên, số điện thoại</label>
                        <input type="text" class="form-control floating"
                               aria-label="Search" aria-describedby="basic-addon2" value="@ViewBag.Keyword" name="keyword">
                        <div class="input-group-append">
                            <button class="btn btn-success" type="submit">
                                <i class="fa fa-search"></i>
                            </button>
                            <button class="btn btn-danger" type="button" onclick="window.location.href='/Customer/Index'">
                                <i class="fa fa-times"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="table-responsive">
                    <table class="table table-striped custom-table">
                        <thead>
                            <tr>
                                <th>
                                    Họ và tên
                                </th>
                                <th>
                                    Giới tính
                                </th>
                                <th>
                                    Ngày sinh
                                </th>
                                <th>
                                    Số điện thoại
                                </th>
                                <th>
                                    Địa chỉ
                                </th>
                                <th>
                                    Ghi chú
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model.Items.Count == 0)
                            {
                                <tr>
                                    <td colspan="7">Không tìm thấy dữ liệu, vui lòng thử lại !!!</td>
                                </tr>
                            }
                            else
                            {
                                foreach (var item in Model.Items)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.FullName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Gender)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.BirthDay)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.PhoneNumber)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Address)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Description)
                                        </td>
                                        <td class="text-right">
                                            <div class="dropdown dropdown-action">
                                                <a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                                    <i class="fa fa-ellipsis-v"></i>
                                                </a>
                                                <div class="dropdown-menu dropdown-menu-right">
                                                    <a href="@Url.Action("Details", "Customer", new { id = item.Id })" class="dropdown-item">
                                                        <i class="fa fa-bars"></i> Chi tiết
                                                    </a>
                                                    <a href="@Url.Action("Edit", "Customer", new { id = item.Id })" class="dropdown-item">
                                                        <i class="fa fa-edit"></i> Sửa
                                                    </a>
                                                    <a href="@Url.Action("Delete", "Customer", new { id = item.Id })" class="dropdown-item" data-toggle="modal" data-target="#delete_customer">
                                                        <i class="fa fa-trash"></i> Xóa
                                                    </a>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
                @await Component.InvokeAsync("Pager", Model)
            </div>
        </div>
        @*end of content*@
    </div>
</div>
<div id="delete_customer" class="modal fade delete-modal" role="dialog">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body text-center">
                <img src="~/assets/img/delete.png" alt="" width="50" height="46">
                <h3>Xóa thông tin khách hàng?</h3>
                <div class="m-t-20">
                    <a href="#" class="btn btn-white" data-dismiss="modal">Hủy</a>
                    <button type="submit" class="btn btn-danger">Xác nhận</button>
                </div>
            </div>
        </div>
    </div>
</div>

DentalManagement.Admin/Views/Customer/Update.cshtml
@model DentalManagement.ViewModels.Catalog.Customers.CustomerUpdateRequest

@{
    ViewData["Title"] = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Update</h1>

<h4>CustomerUpdateRequest</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Customer" asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthDay" class="control-label"></label>
                <input asp-for="BirthDay" class="form-control" />
                <span asp-validation-for="BirthDay" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmailAddress" class="control-label"></label>
                <input asp-for="EmailAddress" class="form-control" />
                <span asp-validation-for="EmailAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdentifyCard" class="control-label"></label>
                <input asp-for="IdentifyCard" class="form-control" />
                <span asp-validation-for="IdentifyCard" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModifiedDate" class="control-label"></label>
                <input asp-for="ModifiedDate" class="form-control" />
                <span asp-validation-for="ModifiedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModifiedBy" class="control-label"></label>
                <input asp-for="ModifiedBy" class="form-control" />
                <span asp-validation-for="ModifiedBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>