DentalManagement.Admin/Controllers/Components/PagerViewComponent.cs
using DentalManagement.ViewModels.Common;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DentalManagement.Admin.Controllers.Components
{
    public class PagerViewComponent : ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync(PagedResultBase result)
        {
            return Task.FromResult((IViewComponentResult)View("Default", result));
        }
    }
}

DentalManagement.Admin/Controllers/InvoiceController.cs
using DentalManagement.ApiIntegration.ApiIntegrations;
using DentalManagement.Utilities.Constants;
using DentalManagement.ViewModels.Catalog.Invoices;
using DentalManagement.ViewModels.Catalog.Invoices.InvoiceDetails;
using DentalManagement.ViewModels.Common;
using DentalManagement.Data.Enums;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Build.Framework;
using DentalManagement.Data.Entities;

namespace DentalManagement.Admin.Controllers
{
    [Authorize]
    public class InvoiceController : BaseController
    {
        private readonly IInvoiceApiClient _invoiceApiClient;
        private readonly IProductApiClient _productApiClient;
        private readonly IConfiguration _configuration;
        public InvoiceController(IInvoiceApiClient invoiceApiClient, IProductApiClient productApiClient,IConfiguration configuration)
        {
            _invoiceApiClient = invoiceApiClient;
            _productApiClient = productApiClient;
            _configuration = configuration;
        }
        public async Task<IActionResult> Index(string keyword, int pageIndex = 1, int pageSize = 10)
        {
            ViewBag.Keyword = keyword;
            var request = new GetInvoicePagingRequest()
            {
                Keyword = keyword,
                PageIndex = pageIndex,
                PageSize = pageSize
            };
            var result = await _invoiceApiClient.GetAllPaging(request);
            return View(result.Data);
        }

        [HttpGet]
        public async Task<IActionResult> GetById(int invoiceId)
        {
            var result = await _invoiceApiClient.GetbyId(invoiceId);
            return Ok(result.Data);
        }

        [HttpGet]
        public async Task<IActionResult> GetCurrentInvoiceProcessingList(int id)
        {
            var invoice = await _invoiceApiClient.GetbyId(id);
            HttpContext.Session.SetString(SystemConstants.InvoiceSession, JsonConvert.SerializeObject(invoice.Data));
            return Ok(invoice.Data);
        }

        [HttpPost]
        public async Task<IActionResult> AddProductToMedicalInvoice(int[] productIds)
        {
            var currentInvoice = new InvoiceViewModel();
            var currentInvoiceDetailList = new List<InvoiceDetailViewModel>();
            var invoiceSessionKey = HttpContext.Session.GetString(SystemConstants.InvoiceSession);
            if (invoiceSessionKey != null)
            {
                currentInvoice = JsonConvert.DeserializeObject<InvoiceViewModel>(invoiceSessionKey);
            }

            foreach (var id in productIds)
            {
                var product = await _productApiClient.GetById(id);
                decimal quantity = 1;
                if (currentInvoiceDetailList.Any(x => x.ProductId == id))
                {
                    quantity = currentInvoiceDetailList.First(x => x.ProductId == id).Quantity + 1;
                    currentInvoiceDetailList.Remove(currentInvoiceDetailList.Single(x => x.ProductId == id));
                }
                var item = new InvoiceDetailViewModel()
                {
                    ProductId = id,
                    ProductName = product.Data.Name,
                    UnitPrice = product.Data.UnitPrice,
                    Quantity = quantity,
                    ItemAmount = product.Data.UnitPrice * quantity,
                    CompletedDate = null,
                    Status = Status.Processing
                };
                currentInvoiceDetailList.Add(item);
            }
            currentInvoice.InvoiceDetailViewModels = currentInvoiceDetailList;
            currentInvoice.TotalInvoiceAmount = currentInvoiceDetailList.Sum(x => x.ItemAmount) - currentInvoice.TotalDiscountAmount;
            currentInvoice.RemainAmount = currentInvoice.TotalInvoiceAmount - currentInvoice.PrepaymentAmount;
            HttpContext.Session.SetString(SystemConstants.InvoiceSession, JsonConvert.SerializeObject(currentInvoice));
            return Ok(currentInvoice);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateCurrentInvoiceProcessingList(int[] productIds)
        {
            var currentInvoice = new InvoiceViewModel();
            var invoiceSessionKey = HttpContext.Session.GetString(SystemConstants.InvoiceSession);
            if (invoiceSessionKey != null)
            {
                currentInvoice = JsonConvert.DeserializeObject<InvoiceViewModel>(invoiceSessionKey);
            }
            var currentInvoiceDetailList = currentInvoice.InvoiceDetailViewModels.ToList();
            foreach (var id in productIds)
            {
                var product = await _productApiClient.GetById(id);
                decimal quantity = 1;
                if (currentInvoiceDetailList.Any(x => x.ProductId == id))
                {
                    quantity = currentInvoiceDetailList.First(x => x.ProductId == id).Quantity + 1;
                    currentInvoiceDetailList.Remove(currentInvoiceDetailList.Single(x => x.ProductId == id));
                }
                var item = new InvoiceDetailViewModel()
                {
                    ProductId = id,
                    ProductName = product.Data.Name,
                    UnitPrice = product.Data.UnitPrice,
                    Quantity = quantity,
                    ItemAmount = product.Data.UnitPrice * quantity,
                    CompletedDate = null,
                    Status = Status.Processing
                };
                currentInvoiceDetailList.Add(item);
            }
            currentInvoice.InvoiceDetailViewModels = currentInvoiceDetailList;
            currentInvoice.TotalInvoiceAmount = currentInvoiceDetailList.Sum(x => x.ItemAmount) - currentInvoice.TotalDiscountAmount;
            currentInvoice.RemainAmount = currentInvoice.TotalInvoiceAmount - currentInvoice.PrepaymentAmount;
            HttpContext.Session.SetString(SystemConstants.InvoiceSession, JsonConvert.SerializeObject(currentInvoice));
            return Ok(currentInvoice);
        }

        [HttpPost]
        public IActionResult UpdateProductQuantity(int productId, int productQuantity)
        {
            var invoiceSessionKey = HttpContext.Session.GetString(SystemConstants.InvoiceSession);
            var currentInvoice = new InvoiceViewModel();
            if (invoiceSessionKey != null)
            {
                currentInvoice = JsonConvert.DeserializeObject<InvoiceViewModel>(invoiceSessionKey);
            }
            foreach (var item in currentInvoice.InvoiceDetailViewModels)
            {
                if (item.ProductId == productId)
                {
                    if (productQuantity == 0)
                    {
                        currentInvoice.InvoiceDetailViewModels.Remove(item);
                        break;
                    }
                    item.Quantity = productQuantity;
                    item.ItemAmount = item.UnitPrice * item.Quantity;
                }
            }
            var totalInvoiceAmount = currentInvoice.InvoiceDetailViewModels.Sum(x => x.ItemAmount);
            var prepaymentAmount = currentInvoice.PrepaymentAmount;
            var totalDiscountAmount = currentInvoice.TotalDiscountAmount;
            currentInvoice.TotalInvoiceAmount = totalInvoiceAmount - totalDiscountAmount;
            currentInvoice.RemainAmount = totalInvoiceAmount - totalDiscountAmount - prepaymentAmount;
            HttpContext.Session.SetString(SystemConstants.InvoiceSession, JsonConvert.SerializeObject(currentInvoice));
            return Ok(currentInvoice);
        }

        [HttpPost]
        public IActionResult UpdateTotalInvoiceAmount(decimal totalDiscountAmount, decimal prepaymentAmount)
        {
            var invoiceSessionKey = HttpContext.Session.GetString(SystemConstants.InvoiceSession);
            var currentInvoice = new InvoiceViewModel();
            if (invoiceSessionKey != null)
            {
                currentInvoice = JsonConvert.DeserializeObject<InvoiceViewModel>(invoiceSessionKey);
            }
            var totalInvoiceAmount = currentInvoice.InvoiceDetailViewModels.Sum(x => x.ItemAmount);
            currentInvoice.TotalDiscountAmount = totalDiscountAmount;
            currentInvoice.PrepaymentAmount = prepaymentAmount;
            currentInvoice.TotalInvoiceAmount = totalInvoiceAmount - totalDiscountAmount;
            currentInvoice.RemainAmount = totalInvoiceAmount - totalDiscountAmount - prepaymentAmount;
            HttpContext.Session.SetString(SystemConstants.InvoiceSession, JsonConvert.SerializeObject(currentInvoice));
            return Ok(currentInvoice);
        }

        [HttpPost]
        public async Task<IActionResult> Create(int customerId)
        {
            var invoiceSessionKey = HttpContext.Session.GetString(SystemConstants.InvoiceSession);
            if (invoiceSessionKey == null)
            {
                TempData["errorMsg"] = SystemConstants.AppErrorMessage.Create;
            }
            else
            {
                var currentInvoice = JsonConvert.DeserializeObject<InvoiceViewModel>(invoiceSessionKey);
                if (currentInvoice.InvoiceDetailViewModels.Any())
                {
                    var currentInvoiceDetailList = new List<InvoiceDetailCreateRequest>();
                    foreach (var item in currentInvoice.InvoiceDetailViewModels)
                    {
                        currentInvoiceDetailList.Add(new InvoiceDetailCreateRequest()
                        {
                            ProductId = item.ProductId,
                            ItemDiscountPercent = item.ItemDiscountPercent,
                            ItemDiscountAmount = item.ItemDiscountAmount,

DentalManagement.Admin/Views/Invoice/Index.cshtml
@using DentalManagement.ViewModels.Common
@model PagedResult<DentalManagement.ViewModels.Catalog.Invoices.InvoiceViewModel>

@{
    ViewData["Title"] = "Danh sách hoá đơn";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Trang chủ</a></li>
        <li class="breadcrumb-item active">Hoá đơn</li>
    </ol>
    <h1 class="h3 mb-2 text-gray-800">Danh sách hoá đơn</h1>
    <div class="row">
        <div class="col-md-6 col-xs-12">
            <a type="button" class="btn btn-outline-primary" asp-action="Index" asp-controller="Bill">
                <i class="fa fa-user-plus"></i>
                Tạo mới
            </a>
        </div>
        <div class="col-md-6 col-xs-12">
            <form asp-action="Index" asp-controller="Invoice" method="get">
                <div class="input-group">
                    <input type="date" class="form-control border-1 small"
                           aria-label="Search" aria-describedby="basic-addon2" value="@ViewBag.Keyword" name="keyword">
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="submit">
                            <i class="fas fa-search fa-sm"></i>
                        </button>
                        <button class="btn btn-outline-primary" type="button" onclick="window.location.href='/Invoice/Index'">
                            X
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <hr />
    <!--number of record-->
    <div class="row">
        <form asp-action="Index" asp-controller="Invoice" method="get" name="pageSize">
            <div class="form-group">
                <div class="col-md-12">
                    <select class="form-control" onchange="numberOfRecords()">
                        <option value="10" selected>Số lượng hiển thị</option>
                        <option value="20">20 hoá đơn</option>
                        <option value="50">50 hoá đơn</option>
                        <option value="100">100 hoá đơn</option>
                    </select>
                </div>
            </div>
        </form>
    </div>
    <div class="card shadow mb-4">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-sm" width="100%" cellspacing="0">
                    <thead class="thead-dark">
                        <tr>
                            <th>
                                Số hoá đơn
                            </th>
                            <th>
                                Khách hàng
                            </th>
                            <th>
                                Ngày tạo
                            </th>
                            <th>
                                Giảm giá
                            </th>
                            <th>
                                Thành tiền
                            </th>
                            <th>
                                Thanh toán
                            </th>
                            <th>
                                Ghi chú
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model.Items.Count == 0)
                        {
                            <tr>
                                <td colspan="8">Không có kết quả</td>
                            </tr>
                        }
                        else
                        {
                            foreach (var item in Model.Items)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Id)
                                    </td>
                                    <td>
                                        @*@Html.DisplayFor(modelItem => item.CustomerViewModel.FullName)*@
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.CreatedDate)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.TotalDiscountAmount)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.TotalInvoiceAmount)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.PrepaymentAmount)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Description)
                                    </td>
                                    <td>
                                        @Html.ActionLink(" Sửa", "Edit", new { id = item.Id }) |
                                        @Html.ActionLink("Xem", "Details", new { id = item.Id }) |
                                        @Html.ActionLink(" Xóa", "Delete", new { id = item.Id })
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
            @await Component.InvokeAsync("Pager", Model)
        </div>
    </div>
</div>